Feature/优化选曲UI
IPOL-Studio/CyanStars pull request #229
Opened 2024-05-09 17:22 UTC by Chen-Luan

2024-05-10 03:12 UTC, memorydream reviewed
记得补上 namespace

2024-05-10 03:12 UTC, memorydream commented on Cyan-Stars/Assets/Scripts/Gameplay/MusicGame/UI/MapSelection/StaffLabel.cs
> +    public GameObject NameFrame;
这些是不是都只用来 `GetComponent` 了？建议直接使用对应的 Component 类型而不是 GameObject

如果只是为了暴露到 Inspector，建议使用 [SerializeField] 修饰 private field

2024-05-10 03:12 UTC, memorydream commented on Cyan-Stars/Assets/Scripts/Gameplay/MusicGame/UI/MapSelection/PageController.cs
> +        { return; }
格式修正

2024-05-10 03:12 UTC, memorydream commented on Cyan-Stars/Assets/Scripts/Gameplay/MusicGame/UI/MapSelection/PageController.cs
> +    public GameObject StarsGenerator;
同上，private + 使用具体需要的类型

2024-05-10 03:12 UTC, memorydream commented on Cyan-Stars/Assets/Scripts/Gameplay/MusicGame/UI/MapSelection/PageControlAble.cs
> +    public TMP_Text[] TextMeshes;
纯运行时数据使用 property，不会序列化，默认也不会在 Inspector 中可见

2024-05-10 03:12 UTC, memorydream commented on Cyan-Stars/Assets/Scripts/Gameplay/MusicGame/UI/MapSelection/StarsGenerator.cs
> +                { continue; }   // 换一颗星星吧
格式，这个下面还有一些相同的格式问题

2024-05-11 07:05 UTC, memorydream requested changes

2024-05-11 07:05 UTC, memorydream commented on Cyan-Stars/Assets/Scripts/Gameplay/MusicGame/UI/MapSelection/PageControlAble.cs
> +namespace SyanStars.Gameplay.MapSelection
按照当前规范，namespace 应为 `CyanStarts.Gameplay.MusicGame`

2024-05-11 07:30 UTC, memorydream commented on Cyan-Stars/Assets/Scripts/Gameplay/MusicGame/UI/MapSelection/PageControlAble.cs
> +            RectTransform.localScale = new Vector3(x, y, z);
RectTransform.localScale = Size + SizeParallax * dp;

2024-05-11 07:30 UTC, memorydream commented on Cyan-Stars/Assets/Scripts/Gameplay/MusicGame/UI/MapSelection/StaffLabel.cs
> +            textMeshes = new List<TMP_Text>(GetComponentsInChildren<TMP_Text>());
```cs
private Image[] images;
private TMP_Text[] textMeshes;

images = GetComponentsInChildren<Image>();
textMeshes = GetComponentsInChildren<TMP_Text>();
```

2024-05-11 07:30 UTC, memorydream commented on Cyan-Stars/Assets/Scripts/Gameplay/MusicGame/UI/MapSelection/MapSelectionPanel.cs
> +            if (mapItem.Data.MapManifest.StaffInfo == "")
```cs
if (string.IsNullOrEmpty(mapItem.Data.MapManifest.StaffInfo) || string.IsNullOrWhitespace(mapItem.Data.MapManifest.StaffInfo))
```

2024-05-30 11:24 UTC, merged

2024-05-30 11:24 UTC, Chen-Luan commented
这个pr先这样，之后再进行重构